name: Test and Build
on: 
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v3.0.0
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn test
    - run: yarn build